name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly, 1.63]

    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
    - run: |
        rustup set profile minimal
        rustup install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}

        cargo check --features "netlink"
        cargo check --no-default-features --features "std netlink"
        cargo check --no-default-features --features "no_std netlink"
        cargo check --no-default-features --features "no_std general errno"

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      # -D warnings is commented out in our install-rust action; re-add it here.
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: stable

    - run: >
        rustup target add
        x86_64-unknown-linux-musl
        x86_64-unknown-linux-gnux32
        i686-unknown-linux-gnu
        i686-unknown-linux-musl
        riscv64gc-unknown-linux-gnu
        aarch64-unknown-linux-gnu
        aarch64-unknown-linux-musl
        powerpc64le-unknown-linux-gnu
        armv5te-unknown-linux-gnueabi
        mipsel-unknown-linux-gnu
        mips64el-unknown-linux-gnuabi64
    - run: cargo check --tests -vv
    - run: cargo check --tests -vv --target=x86_64-unknown-linux-musl
    - run: cargo check --tests -vv --target=x86_64-unknown-linux-gnux32
    - run: cargo check --tests -vv --target=i686-unknown-linux-gnu
    - run: cargo check --tests -vv --target=i686-unknown-linux-musl
    - run: cargo check --tests -vv --target=riscv64gc-unknown-linux-gnu
    - run: cargo check --tests -vv --target=aarch64-unknown-linux-gnu
    - run: cargo check --tests -vv --target=aarch64-unknown-linux-musl
    - run: cargo check --tests -vv --target=powerpc64le-unknown-linux-gnu
    - run: cargo check --tests -vv --target=armv5te-unknown-linux-gnueabi
    - run: cargo check --tests -vv --target=mipsel-unknown-linux-gnu
    - run: cargo check --tests -vv --target=mips64el-unknown-linux-gnuabi64

  gen:
    name: Update generated files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt install libclang-dev
        cd gen && cargo run --release
        git diff --exit-code
