name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]

    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup set profile minimal
        rustup install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}

        cargo check --features "netlink"
        cargo check --no-default-features --features "std netlink"
        cargo check --no-default-features --features "no_std netlink"
        cargo check --no-default-features --features "no_std general errno"

  gen:
    name: Update generated files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt install libclang-dev
        cd gen && cargo run --release
        git diff --exit-code
